baseURL = "https://edu3dmodel.com/"
languageCode = "tr-tr"
title = "Edu 3D Model Dünyası"
theme = "PaperMod"

# ... baseURL, languageCode gibi satırların altına ...

[outputs]
  home = ["HTML", "RSS", "JSON"] # Arama indeksi için JSON çıkışı eklendi

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup.goldmark.renderer]
  unsafe = true

[params]
  description = "3D yazıcılar gözünü korkutmasın! Edu 3D Model Dünyası'nda A'dan Z'ye her şeyi keyifle öğren. Sorularını sor, projelerini paylaş, ailemize katıl!"
  author = "uurk55"
  defaultTheme = "light"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowRelatedPosts = true
  mainSections = ["posts"]

  # YORUM SİSTEMİ AYARLARI
  [params.giscus]
    repo = "uurk55/uurk55.github.io"
    repoId = "R_kgDOPBdhHw"
    category = "Announcements"
    categoryId = "DIC_kwDOPBdhH84CsGnw"
    lang = "tr"
    mapping = "pathname"
    reactionsEnabled = "1"
    emitMetadata = "0"
    inputPosition = "top"
    theme = "light"
    loading = "lazy"

[params.profileMode]
  enabled = true
  title = "Edu 3D Model Dünyası"
  subtitle = "3D yazıcılar gözünü korkutmasın! Edu 3D Model Dünyası'nda A'dan Z'ye her şeyi keyifle öğren. Sorularını sor, projelerini paylaş, ailemize katıl!"
  imageUrl = "/logo.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Edu 3D Model Logosu"
  
  [[params.profileMode.buttons]]
    name = "Yazılarım"
    url = "/posts"
  [[params.profileMode.buttons]]
    name = "Hakkımda"
    url = "/about"
  [[params.profileMode.buttons]]
    name = "İletişim"
    url = "/iletisim"


[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/edu3dmodel/"
[[params.socialIcons]]
  name = "Mail"
  url = "mailto:edu3dmodel@gmail.com"


# --- YENİ ve SADELEŞTİRİLMİŞ MENÜ YAPILANDIRMASI ---
[menu]
  [[menu.main]]
    name = "Anasayfa"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Tüm Yazılar"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    name = "Kategoriler"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    name = "Hakkımda"
    url = "/hakkimda/" 
    weight = 40

  [[menu.main]]
    name = "İletişim"
    url = "/iletisim/"
    weight = 50

  # [[menu.main]]
   # name = "Tavsiyelerim"
   # url = "/tavsiyelerim/"
   # weight = 60

  [[menu.main]]
    identifier = "cta-button"
    name = "E-KİTAP HAZIRLANIYOR"
    url = "/ekitap"
    weight = 70
    [menu.main.params]
      is_button = true
      # GitHub Actions testi için deneme