baseURL = "https://edu3dmodel.com/" # <-- GÜNCELLENDİ
languageCode = "tr-tr"
title = "Edu 3D Model Dünyası"
theme = "PaperMod"
# Sayfalama Ayarları (Ana sayfada kaç yazı gösterileceği)
[pagination]
  pagerSize = 5

# ANA PARAMETRELER
[params]
  description = "Fikirlerini 3D Ürüne Dönüştür, Gelir Elde Et!"
  author = "uurk55"
  defaultTheme = "auto" # "light" veya "dark" olarak zorlayabilirsin
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true

  # YAZI SONUNDA BENZER YAZILARI GÖSTER
  ShowRelatedPosts = true


# SOL TARAFTAKİ PROFİL KUTUSU (LOGO BURADA)
[params.profileMode]
  enabled = true
  title = "Edu 3D Model Dünyası"
  subtitle = "Fikirlerini Ürüne Dönüştür"
  imageUrl = "/logo.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Edu 3D Model Logosu"
  
  [[params.profileMode.buttons]]
    name = "Tüm Yazılar"
    url = "/posts"
  
  [[params.profileMode.buttons]]
    name = "Hakkımda"
    url = "/about" # İleride oluşturacağız

  [[params.profileMode.buttons]]
  name = "İletişim"
  url = "/iletisim"

# SOSYAL MEDYA İKONLARI
[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/edu3dmodel/"

# SAĞ ÜST MENÜ
[menu]
  [[menu.main]]
    identifier = "arsiv"
    name = "Arşiv"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "arama"
    name = "Arama"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "etiketler"
    name = "Etiketler"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "iletisim"
    name = "İletişim"
    url = "/iletisim"
    weight = 40
  # SAĞ ÜST MENÜ
  [[menu.main]]
    identifier: "tavsiyelerim"
    name: "Tavsiyelerim"
    url: "/tavsiyelerim"
    weight: 50