baseURL = "https://uurk55.github.io/"
languageCode = "tr-tr"
title = "Edu 3D Model Dünyası"
theme = "PaperMod"

[params]
  description = "Sadece model değil, gelir de üretin. 3D baskı ile pasif geliri öğrenin."
  author = "uurk55"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  
  logo = "logo.png" 
  logo_width = 35 
  logo_height = 35 

[params.homeInfoParams]
  Title = "Hoş Geldiniz! 👋"
  Content = "3D yazıcı tutkusunu pasif gelire dönüştürmek isteyenler için kaynak merkezi."

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/edu3dmodel/"



[menu]
  [[menu.main]]
    identifier = "arsiv"
    name = "Arşiv"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "arama"
    name = "Arama"
    url = "/search/"
    weight = 20