baseURL = "https://edu3dmodel.com/"
languageCode = "tr-tr"
title = "Edu 3D Model Dünyası"
theme = "PaperMod"

# ANA SINIFLANDIRMA (TAXONOMY) TANIMLAMALARI
# Bu bölüm, Hugo'ya 'categories' ve 'tags' adında sınıflandırmalar olduğunu söyler.
[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

# ANA PARAMETRELER BÖLÜMÜ
[params]
  description = "Fikirlerini 3D Ürüne Dönüştür, Gelir Elde Et!"
  author = "uurk55"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowRelatedPosts = true
  mainSections = ["posts"]

# SOL TARAFTAKİ PROFİL KUTUSU
[params.profileMode]
  enabled = true
  title = "Edu 3D Model Dünyası"
  subtitle = "Fikirlerini Ürüne Dönüştür"
  imageUrl = "/logo.png"
  imageWidth = 120
  imageHeight = 120
  imageTitle = "Edu 3D Model Logosu"
  
  [[params.profileMode.buttons]]
    name = "Tüm Yazılar"
    url = "/posts"
  [[params.profileMode.buttons]]
    name = "Hakkımda"
    url = "/about"
  [[params.profileMode.buttons]]
    name = "İletişim"
    url = "/iletisim"
  [[params.profileMode.buttons]]
    name = "Tavsiyelerim"
    url = "/tavsiyelerim"

# SOSYAL MEDYA İKONLARI
[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/edu3dmodel/"

# SAĞ ÜST MENÜ
[menu]
  [[menu.main]]
    identifier = "arsiv"
    name = "Arşiv"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "arama"
    name = "Arama"
    url = "/search/"
    weight = 20
  [[menu.main]]
    identifier = "etiketler"
    name = "Etiketler"
    url = "/tags/"
    weight = 30
  [[menu.main]]
    identifier = "iletisim"
    name = "İletişim"
    url = "/iletisim"
    weight = 40
  [[menu.main]]
    identifier = "tavsiyelerim"
    name = "Tavsiyelerim"
    url = "/tavsiyelerim"
    weight = 50