baseURL = "https://uurk55.github.io/"
languageCode = "tr-tr"
title = "Edu 3D Model Dünyası"
theme = "PaperMod"

[params]
  description = "Sadece model değil, gelir de üretin. 3D baskı ile pasif geliri öğrenin."
  author = "uurk55"
  defaultTheme = "auto"
  ShowShareButtons = true
  ShowReadingTime = true
  
  logo = "logo.png" 
  logo_width = 35 
  logo_height = 35 

[params.homeInfoParams]
  Title = "Hoş Geldiniz! 👋"
  Content = "3D yazıcı tutkusunu pasif gelire dönüştürmek isteyenler için kaynak merkezi."

[[params.socialIcons]]
  name = "instagram"
  url = "https://www.instagram.com/edu3dmodel/"

[params.profileMode]
  enabled = true # Profil modunu aktif et
  title = "Edu 3D Model Dünyası" # Logonun yanında görünecek başlık
  subtitle = "Fikirlerini Ürüne Dönüştür" # Başlığın altındaki alt başlık
  imageUrl = "/logo.png" # Resmin yolu. /static/logo.png'a işaret eder.
  imageWidth = 120 # Resmin genişliği (piksel)
  imageHeight = 120 # Resmin yüksekliği (piksel)
  imageTitle = "Edu 3D Model Logosu" # Resmin üzerine gelince görünecek yazı
  
  [[params.profileMode.buttons]]
    name = "Yazılar"
    url = "/posts"

  [[params.profileMode.buttons]]
    name = "Hakkımda"
    url = "/about" # İleride oluşturacağımız sayfa

[menu]
  [[menu.main]]
    identifier = "arsiv"
    name = "Arşiv"
    url = "/archives/"
    weight = 10
  [[menu.main]]
    identifier = "arama"
    name = "Arama"
    url = "/search/"
    weight = 20